// Copies the ABIs of all three contracts (Multisig, JobMarketplace, MockERC20)
// from Hardhat artifacts into the frontend so the React app can import them
// as typed consts.
//
// Run with: npx hardhat run scripts/copy-abi.ts
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, resolve } from "path";

const ROOT = resolve(__dirname, "..");
const OUT_DIR = join(ROOT, "frontend", "src", "contracts");

type Contract = {
  artifact: string;
  output: string;
  exportName: string;
};

const CONTRACTS: Contract[] = [
  {
    artifact: "artifacts/contracts/Multisig.sol/Multisig.json",
    output: "Multisig.abi.ts",
    exportName: "multisigAbi",
  },
  {
    artifact: "artifacts/contracts/JobMarketplace.sol/JobMarketplace.json",
    output: "JobMarketplace.abi.ts",
    exportName: "jobMarketplaceAbi",
  },
  {
    artifact: "artifacts/contracts/MockERC20.sol/MockERC20.json",
    output: "MockERC20.abi.ts",
    exportName: "erc20Abi",
  },
];

function main() {
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  for (const c of CONTRACTS) {
    const artifactPath = join(ROOT, c.artifact);
    if (!existsSync(artifactPath)) {
      console.warn(`Skipping ${c.exportName}: ${artifactPath} not found (compile first)`);
      continue;
    }
    const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
    const fileBody =
      `// Auto-generated by scripts/copy-abi.ts. Do not edit by hand.\n` +
      `// Source: ${c.artifact}\n\n` +
      `export const ${c.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
    writeFileSync(join(OUT_DIR, c.output), fileBody, "utf8");
    console.log(`ABI copied: ${c.output} (${artifact.abi.length} entries)`);
  }
}

main();
