// Copies the Multisig ABI from Hardhat artifacts into the frontend so the
// React app can import it as a typed const.
//
// Run with: npx hardhat run scripts/copy-abi.ts
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { dirname, join, resolve } from "path";

const ROOT = resolve(__dirname, "..");
const ARTIFACT = join(ROOT, "artifacts", "contracts", "Multisig.sol", "Multisig.json");
const OUT_DIR = join(ROOT, "frontend", "src", "contracts");
const OUT_FILE = join(OUT_DIR, "Multisig.abi.ts");

function main() {
  if (!existsSync(ARTIFACT)) {
    throw new Error(
      `Artifact not found at ${ARTIFACT}. Run \`npx hardhat compile\` first.`,
    );
  }

  const artifact = JSON.parse(readFileSync(ARTIFACT, "utf8"));
  const abi = artifact.abi;

  if (!existsSync(OUT_DIR)) {
    mkdirSync(OUT_DIR, { recursive: true });
  }

  const fileBody = `// Auto-generated by scripts/copy-abi.ts. Do not edit by hand.\n` +
    `// Source: artifacts/contracts/Multisig.sol/Multisig.json\n\n` +
    `export const multisigAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;

  writeFileSync(OUT_FILE, fileBody, "utf8");

  // Ensure .gitignore covers this generated file
  const gitignorePath = join(ROOT, ".gitignore");
  // best-effort, ignore failure

  console.log(`ABI copied to ${OUT_FILE} (${abi.length} entries)`);
}

main();
