// Deploys the Multisig contract with 3 freshly generated signers and a
// 2-of-3 threshold, funds the contract and each signer with test ETH, and
// optionally verifies the source on Etherscan.
//
// On Sepolia the deployer must hold at least ~3.5 ETH (3 signers + contract + gas).
// On a local Hardhat node the test accounts come preloaded.
import { ethers, network, run } from "hardhat";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, resolve } from "path";

const ROOT = resolve(__dirname, "..");
const FRONTEND_ENV_DIR = join(ROOT, "frontend");
const FRONTEND_ENV_FILE = join(FRONTEND_ENV_DIR, ".env");
const SIGNERS_DOC = join(ROOT, "SIGNERS.md");

const FUND_PER_SIGNER = ethers.parseEther("1");
const FUND_CONTRACT = ethers.parseEther("0.5");
const THRESHOLD = 2;
const NUM_SIGNERS = 3;

async function main() {
  const [deployer] = await ethers.getSigners();
  const networkName = network.name;

  console.log("\n=== Multisig Deployment ===");
  console.log(`Network:        ${networkName}`);
  console.log(`Deployer:       ${await deployer.getAddress()}`);
  console.log(`Deployer bal:   ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH\n`);

  // 1. Generate signer wallets
  console.log(`Generating ${NUM_SIGNERS} fresh signer wallets...`);
  const signers = Array.from({ length: NUM_SIGNERS }, () => ethers.Wallet.createRandom().connect(ethers.provider));

  // 2. Fund the signer wallets (skip on real Sepolia unless deployer can afford it)
  const isLocal = networkName === "hardhat" || networkName === "localhost";
  if (isLocal) {
    for (let i = 0; i < signers.length; i++) {
      const tx = await deployer.sendTransaction({ to: signers[i].address, value: FUND_PER_SIGNER });
      await tx.wait();
      console.log(`  Signer ${i + 1} funded: ${signers[i].address} (tx: ${tx.hash})`);
    }
  } else {
    console.log("  Skipping auto-fund of signers (non-local network). Make sure each signer has test ETH for gas.");
  }

  // 3. Deploy Multisig
  const signerAddresses = signers.map((s) => s.address);
  const Multisig = await ethers.getContractFactory("Multisig");
  console.log(`\nDeploying Multisig with ${NUM_SIGNERS} signers and threshold = ${THRESHOLD}...`);
  const multisig = await Multisig.deploy(signerAddresses, THRESHOLD);
  await multisig.waitForDeployment();
  const multisigAddress = await multisig.getAddress();
  const deployTx = multisig.deploymentTransaction();
  console.log(`Multisig deployed: ${multisigAddress}`);
  console.log(`Deploy tx:         ${deployTx?.hash}`);

  // 4. Fund the multisig so it can pay out ETH transfers
  if (isLocal) {
    const tx = await deployer.sendTransaction({ to: multisigAddress, value: FUND_CONTRACT });
    await tx.wait();
    console.log(`Multisig funded:   ${ethers.formatEther(FUND_CONTRACT)} ETH (tx: ${tx.hash})`);
  } else {
    console.log("\nRemember to send some ETH to the multisig address so it can execute value transfers.");
  }

  // 5. Optional Etherscan verification
  if (networkName === "sepolia" && process.env.ETHERSCAN_API_KEY) {
    console.log("\nVerifying on Etherscan...");
    try {
      await run("verify:verify", {
        address: multisigAddress,
        constructorArguments: [signerAddresses, THRESHOLD],
      });
      console.log("Etherscan verification: OK");
    } catch (err) {
      console.warn("Etherscan verification failed (continuing):", (err as Error).message);
    }
  }

  // 6. Persist signer info
  if (!existsSync(FRONTEND_ENV_DIR)) mkdirSync(FRONTEND_ENV_DIR, { recursive: true });

  const envBody = [
    "# Auto-generated by scripts/deploy.ts",
    `VITE_MULTISIG_ADDRESS=${multisigAddress}`,
    `# Optional: WalletConnect Cloud project ID (https://cloud.walletconnect.com)`,
    `VITE_WC_PROJECT_ID=`,
    "",
  ].join("\n");
  writeFileSync(FRONTEND_ENV_FILE, envBody, "utf8");
  console.log(`\nWrote ${FRONTEND_ENV_FILE}`);

  const docLines = [
    `# Multisig Signer Wallets (${networkName})`,
    "",
    `Contract: \`${multisigAddress}\``,
    `Threshold: ${THRESHOLD} of ${NUM_SIGNERS}`,
    "",
    "> These are TEST wallets. Never reuse them for real funds.",
    "",
    ...signers.map(
      (s, i) =>
        `## Signer ${i + 1}\n\n- Address: \`${s.address}\`\n- Private key: \`${s.privateKey}\`\n`,
    ),
  ];
  writeFileSync(SIGNERS_DOC, docLines.join("\n"), "utf8");
  console.log(`Wrote ${SIGNERS_DOC}`);

  console.log("\n=== Summary ===");
  console.log(`Contract: ${multisigAddress}`);
  console.log(`Signers:`);
  signers.forEach((s, i) => console.log(`  ${i + 1}. ${s.address}  pk=${s.privateKey}`));
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
