// Centralised "update frontend with latest deploy info" routine.
// Reads the existing frontend/.env to preserve user-supplied values
// (VITE_ALCHEMY_API_KEY, VITE_WC_PROJECT_ID) and overwrites the
// contract addresses + sync the ABIs.
//
// Used by scripts/deploy.ts and scripts/redeploy-marketplace.ts. Can also
// be invoked standalone after manually editing the .env:
//
//   npx hardhat run scripts/update-frontend.ts -- <MULTISIG> <MARKETPLACE> <TOKEN>

import { execSync } from "child_process";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";

const ROOT = resolve(__dirname, "..");
const FRONTEND_DIR = join(ROOT, "frontend");
const FRONTEND_ENV = join(FRONTEND_DIR, ".env");

const ZERO = "0x0000000000000000000000000000000000000000";

function parseEnv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split(/\r?\n/)) {
    if (!line || line.startsWith("#")) continue;
    const m = line.match(/^([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function isValidAddr(a: string): boolean {
  return /^0x[0-9a-fA-F]{40}$/.test(a) && a.toLowerCase() !== ZERO;
}

export type UpdateArgs = {
  multisig?: string;
  marketplace?: string;
  token?: string;
};

export async function updateFrontend(args: UpdateArgs): Promise<void> {
  if (!existsSync(FRONTEND_DIR)) {
    console.warn(`[update-frontend] ${FRONTEND_DIR} does not exist — skipping`);
    return;
  }

  // 1. Read existing .env to preserve user-supplied keys.
  let existing: Record<string, string> = {};
  if (existsSync(FRONTEND_ENV)) {
    existing = parseEnv(readFileSync(FRONTEND_ENV, "utf8"));
  }

  // 2. Apply new addresses on top.
  const merged: Record<string, string> = {
    ...existing,
    VITE_MULTISIG_ADDRESS: isValidAddr(args.multisig ?? "")
      ? args.multisig!
      : existing.VITE_MULTISIG_ADDRESS ?? ZERO,
    VITE_MARKETPLACE_ADDRESS: isValidAddr(args.marketplace ?? "")
      ? args.marketplace!
      : existing.VITE_MARKETPLACE_ADDRESS ?? ZERO,
    VITE_TOKEN_ADDRESS: isValidAddr(args.token ?? "")
      ? args.token!
      : existing.VITE_TOKEN_ADDRESS ?? ZERO,
  };

  // 3. Re-render as a stable, comment-rich .env.
  const lines = [
    "# Auto-generated by scripts/update-frontend.ts",
    `# Last updated: ${new Date().toISOString()}`,
    "",
    `VITE_MULTISIG_ADDRESS=${merged.VITE_MULTISIG_ADDRESS}`,
    `VITE_MARKETPLACE_ADDRESS=${merged.VITE_MARKETPLACE_ADDRESS}`,
    `VITE_TOKEN_ADDRESS=${merged.VITE_TOKEN_ADDRESS}`,
    "",
    "# Optional: WalletConnect Cloud project ID (https://cloud.walletconnect.com).",
    `VITE_WC_PROJECT_ID=${merged.VITE_WC_PROJECT_ID ?? ""}`,
    "",
    "# Alchemy Sepolia API key (used as the primary RPC endpoint).",
    `# Get one free at https://www.alchemy.com/ and paste it here.`,
    `VITE_ALCHEMY_API_KEY=${merged.VITE_ALCHEMY_API_KEY ?? ""}`,
    "",
  ];
  writeFileSync(FRONTEND_ENV, lines.join("\n"), "utf8");
  console.log(`[update-frontend] wrote ${FRONTEND_ENV}`);
  console.log(`[update-frontend]   multisig   = ${merged.VITE_MULTISIG_ADDRESS}`);
  console.log(`[update-frontend]   marketplace= ${merged.VITE_MARKETPLACE_ADDRESS}`);
  console.log(`[update-frontend]   token      = ${merged.VITE_TOKEN_ADDRESS}`);
  if (!merged.VITE_ALCHEMY_API_KEY) {
    console.warn(
      `[update-frontend] ⚠ VITE_ALCHEMY_API_KEY is empty — RPC will fall back to publicnode`,
    );
  }

  // 4. Sync ABIs so the frontend sees the latest custom errors / events.
  console.log("[update-frontend] syncing ABIs...");
  try {
    execSync("npx hardhat run scripts/copy-abi.ts", {
      cwd: ROOT,
      stdio: "inherit",
    });
  } catch (e) {
    console.warn(`[update-frontend] ABI sync failed:`, (e as Error).message);
  }

  console.log("\n[update-frontend] ✓ Frontend .env + ABIs updated.");
  console.log(
    "[update-frontend] Reminder: restart the Vite dev server so the new env vars are picked up.",
  );
}

// CLI entry point.
async function main() {
  const cliArgs = process.argv.slice(2);
  const flag = (name: string): string | undefined => {
    const idx = cliArgs.indexOf(name);
    return idx >= 0 ? cliArgs[idx + 1] : undefined;
  };
  await updateFrontend({
    multisig: flag("--multisig"),
    marketplace: flag("--marketplace"),
    token: flag("--token"),
  });
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});